/*
 *
 * Alerts constants
 *
 */
export const types ={
    SUCCESS_SNACKBAR : 'SUCCESS_SNACKBAR',
    ERROR_SNACKBAR : 'ERROR_SNACKBAR',
    WARNING_SNACKBAR : 'WARNING_SNACKBAR',
    CLEAR_SNACKBAR :'CLEAR_SNACKBAR'
}

